USE springlister_db;

TRUNCATE products;

insert into products (id, name, price) values (1, 'Table Cloth 81x81 Colour', '$10.87');
insert into products (id, name, price) values (2, 'Cheese - Parmesan Grated', '$10.69');
insert into products (id, name, price) values (3, 'Lettuce - Romaine, Heart', '$2.32');
insert into products (id, name, price) values (4, 'Oil - Safflower', '$5.46');
insert into products (id, name, price) values (5, 'Chocolate - White', '$3.49');
insert into products (id, name, price) values (6, 'Scallops - Live In Shell', '$5.38');
insert into products (id, name, price) values (7, 'Lid - 0090 Clear', '$1.81');
insert into products (id, name, price) values (8, 'Apricots Fresh', '$14.35');
insert into products (id, name, price) values (9, 'Wine - Marlbourough Sauv Blanc', '$14.78');
insert into products (id, name, price) values (10, 'Amarula Cream', '$5.97');
insert into products (id, name, price) values (11, 'Rice Pilaf, Dry,package', '$12.28');
insert into products (id, name, price) values (12, 'Cherries - Fresh', '$7.55');
insert into products (id, name, price) values (13, 'Wine - Red, Pinot Noir, Chateau', '$14.74');
insert into products (id, name, price) values (14, 'Langers - Mango Nectar', '$4.12');
insert into products (id, name, price) values (15, 'Juice - Ocean Spray Kiwi', '$12.90');
insert into products (id, name, price) values (16, '7up Diet, 355 Ml', '$1.54');
insert into products (id, name, price) values (17, 'Carbonated Water - Wildberry', '$6.82');
insert into products (id, name, price) values (18, 'Glass Clear 8 Oz', '$14.27');
insert into products (id, name, price) values (19, 'Mushroom - Trumpet, Dry', '$9.72');
insert into products (id, name, price) values (20, 'Cheese - Montery Jack', '$9.09');
insert into products (id, name, price) values (21, 'Beef - Tender Tips', '$5.71');
insert into products (id, name, price) values (22, 'Aspic - Light', '$7.50');
insert into products (id, name, price) values (23, 'Wine - Vineland Estate Semi - Dry', '$13.11');
insert into products (id, name, price) values (24, 'Wine - Placido Pinot Grigo', '$8.07');
insert into products (id, name, price) values (25, 'Appetizer - Veg Assortment', '$5.42');
insert into products (id, name, price) values (26, 'Bread Bowl Plain', '$13.40');
insert into products (id, name, price) values (27, 'Trout - Rainbow, Frozen', '$6.03');
insert into products (id, name, price) values (28, 'Juice Peach Nectar', '$10.41');
insert into products (id, name, price) values (29, 'Rabbit - Whole', '$4.36');
insert into products (id, name, price) values (30, 'Pastry - Mini French Pastries', '$6.45');
insert into products (id, name, price) values (31, 'Oil - Truffle, White', '$4.08');
insert into products (id, name, price) values (32, 'Garbage Bags - Clear', '$8.68');
insert into products (id, name, price) values (33, 'Cheese - Brie Roitelet', '$10.20');
insert into products (id, name, price) values (34, 'Creme De Cacao White', '$5.66');
insert into products (id, name, price) values (35, 'Sauce Bbq Smokey', '$5.55');
insert into products (id, name, price) values (36, 'Pepper - Chipotle, Canned', '$13.28');
insert into products (id, name, price) values (37, 'Spaghetti Squash', '$5.21');
insert into products (id, name, price) values (38, 'Uniform Linen Charge', '$1.81');
insert into products (id, name, price) values (39, 'Pepper - Paprika, Spanish', '$11.69');
insert into products (id, name, price) values (40, 'Mustard - Dry, Powder', '$5.41');
insert into products (id, name, price) values (41, 'Jam - Raspberry,jar', '$3.77');
insert into products (id, name, price) values (42, 'Drambuie', '$4.52');
insert into products (id, name, price) values (43, 'Dehydrated Kelp Kombo', '$3.28');
insert into products (id, name, price) values (44, 'Nantucket Cranberry Juice', '$13.74');
insert into products (id, name, price) values (45, 'Oil - Avocado', '$2.13');
insert into products (id, name, price) values (46, 'Boogies', '$13.33');
insert into products (id, name, price) values (47, 'Bagel - Everything Presliced', '$0.33');
insert into products (id, name, price) values (48, 'Table Cloth 54x72 Colour', '$5.99');
insert into products (id, name, price) values (49, 'Salt - Sea', '$9.86');
insert into products (id, name, price) values (50, 'Cheese - Boursin, Garlic / Herbs', '$5.51');